### ISSUE TITLE
How to use newer version?

### ISSUE THREAD

**Issue by nekotako1** [yy556023/GBFRSkillEditor#5]
I'm just dump and don't know how to use new version. I'm stuck in Skill edit 1.0.5. Do it need to merge files or something?

**Comment by yy556023** [comment]
pls check locale folder's file 
I have updated alpha beta gamma's Id in this version

**Comment by nekotako1** [comment]
so i only have to replace new locale file?

**Comment by yy556023** [comment]
Y

**Comment by nekotako1** [comment]
Thank you!
